// auto generated by c2z
#include <new>

#include "../../../../../dep/ztf/src/dep/common/tfalias/Common_3/Utilities/Interfaces/ILog.h"

extern "C" void _1__EnableInteractiveMode_(bool isInteractivenMode) { ::_EnableInteractiveMode(isInteractivenMode); }
extern "C" bool _1__IsInteractiveMode_() { return ::_IsInteractiveMode(); }
extern "C" void _1__FailedAssertImpl_(const char * file, int line, const char * statement, const char * message) { ::_FailedAssertImpl(file, line, statement, message); }
extern "C" void _1__OutputDebugStringV_(const char * str, va_list args) { ::_OutputDebugStringV(str, args); }
extern "C" void _1__PrintUnicode_(const char * str, bool error) { ::_PrintUnicode(str, error); }
