// auto generated by c2z
const std = @import("std");
//const cpp = @import("cpp");

extern fn _1__EnableInteractiveMode_(isInteractivenMode: bool) void;
pub const _EnableInteractiveMode = _1__EnableInteractiveMode_;

extern fn _1__IsInteractiveMode_() bool;
pub const _IsInteractiveMode = _1__IsInteractiveMode_;

extern fn _1__FailedAssertImpl_(file: [*c]const u8, line: c_int, statement: [*c]const u8, message: [*c]const u8) void;
pub const _FailedAssertImpl = _1__FailedAssertImpl_;

extern fn _1__OutputDebugStringV_(str: [*c]const u8, args: [*c]u8) void;
pub const _OutputDebugStringV = _1__OutputDebugStringV_;

extern fn _1__PrintUnicode_(str: [*c]const u8, __error: bool) void;
pub const _PrintUnicode = _1__PrintUnicode_;
